# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ private-actions ]
    # 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:         
      - name: Copy Actions
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          cp -r ~/actions .
          matcher_path=$GITHUB_WORKSPACE/actions/problem-matcher.json
           
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: ./actions/checkout
        continue-on-error: true

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pwd
        
      - uses: ./actions/setup-node
        with:
          node-version: '14'
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -la
          git --version
          node --version
